"""installment plans

Revision ID: 96d2eb7209c7
Revises: 11d084e85692
Create Date: 2026-09-30 16:36:39.506685
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "96d2eb7209c7"
down_revision: str | None = "11d084e85692"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "installment_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=120), nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("n_months", sa.Integer(), nullable=False),
        sa.Column("interest_free", sa.Boolean(), nullable=False),
        sa.Column("purchase_date", sa.Date(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("is_impulse", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "n_months BETWEEN 2 AND 48", name=op.f("ck_installment_plans_n_months_range")
        ),
        sa.CheckConstraint("total > 0", name=op.f("ck_installment_plans_total_positive")),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
            name=op.f("fk_installment_plans_card_id_cards"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_installment_plans_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_installment_plans")),
    )
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.add_column(sa.Column("installment_plan_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("installment_number", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_expenses_installment_plan_id"), ["installment_plan_id"], unique=False
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_expenses_installment_plan_id"),
            ["installment_plan_id", "installment_number"],
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_expenses_installment_plan_id_installment_plans"),
            "installment_plans",
            ["installment_plan_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_expenses_installment_plan_id_installment_plans"), type_="foreignkey"
        )
        batch_op.drop_constraint(batch_op.f("uq_expenses_installment_plan_id"), type_="unique")
        batch_op.drop_index(batch_op.f("ix_expenses_installment_plan_id"))
        batch_op.drop_column("installment_number")
        batch_op.drop_column("installment_plan_id")

    op.drop_table("installment_plans")
    # ### end Alembic commands ###
