"""incomes payments checks

Revision ID: 717a7639d00f
Revises: e9025e0b6791
Create Date: 2026-09-30 17:43:35.996646
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "717a7639d00f"
down_revision: str | None = "e9025e0b6791"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card_payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("cycle", sa.String(length=7), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_card_payments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
            name=op.f("fk_card_payments_card_id_cards"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_payments")),
    )
    with op.batch_alter_table("card_payments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_card_payments_card_id"), ["card_id"], unique=False)

    op.create_table(
        "recurring_incomes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "salary",
                "freelance",
                "bonus",
                "other",
                name="incomekind",
                native_enum=False,
                length=15,
            ),
            nullable=False,
        ),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column(
            "frequency",
            sa.Enum(
                "monthly", "semimonthly", "yearly", name="frequency", native_enum=False, length=15
            ),
            nullable=False,
        ),
        sa.Column("day_of_month", sa.Integer(), nullable=False),
        sa.Column("second_day", sa.Integer(), nullable=True),
        sa.Column("month_of_year", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("next_run", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("amount_is_estimate", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "frequency != 'semimonthly' OR (second_day BETWEEN 1 AND 31 AND second_day != day_of_month)",
            name=op.f("ck_recurring_incomes_semimonthly_has_second_day"),
        ),
        sa.CheckConstraint(
            "frequency != 'yearly' OR month_of_year BETWEEN 1 AND 12",
            name=op.f("ck_recurring_incomes_yearly_has_month"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_recurring_incomes_amount_positive")),
        sa.CheckConstraint(
            "day_of_month BETWEEN 1 AND 31", name=op.f("ck_recurring_incomes_day_range")
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["cards.id"],
            name=op.f("fk_recurring_incomes_account_id_cards"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recurring_incomes")),
    )
    op.create_table(
        "statement_checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("cycle", sa.String(length=7), nullable=False),
        sa.Column("bank_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
            name=op.f("fk_statement_checks_card_id_cards"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_statement_checks")),
        sa.UniqueConstraint("card_id", "cycle", name=op.f("uq_statement_checks_card_id")),
    )
    op.create_table(
        "incomes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(length=120), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "salary",
                "freelance",
                "bonus",
                "other",
                name="incomekind",
                native_enum=False,
                length=15,
            ),
            nullable=False,
        ),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("recurring_income_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_incomes_amount_positive")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["cards.id"],
            name=op.f("fk_incomes_account_id_cards"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["recurring_income_id"],
            ["recurring_incomes.id"],
            name=op.f("fk_incomes_recurring_income_id_recurring_incomes"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incomes")),
        sa.UniqueConstraint(
            "recurring_income_id", "date", name=op.f("uq_incomes_recurring_income_id")
        ),
    )
    with op.batch_alter_table("incomes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_incomes_date"), ["date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_incomes_recurring_income_id"), ["recurring_income_id"], unique=False
        )

    with op.batch_alter_table("recurring_charges", schema=None) as batch_op:
        batch_op.add_column(sa.Column("second_day", sa.Integer(), nullable=True))
        # Autogenerate doesn't detect CHECK constraints on existing tables.
        batch_op.create_check_constraint(
            "semimonthly_has_second_day",
            "frequency != 'semimonthly' OR "
            "(second_day BETWEEN 1 AND 31 AND second_day != day_of_month)",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recurring_charges", schema=None) as batch_op:
        batch_op.drop_constraint(
            op.f("ck_recurring_charges_semimonthly_has_second_day"), type_="check"
        )
        batch_op.drop_column("second_day")

    with op.batch_alter_table("incomes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_incomes_recurring_income_id"))
        batch_op.drop_index(batch_op.f("ix_incomes_date"))

    op.drop_table("incomes")
    op.drop_table("statement_checks")
    op.drop_table("recurring_incomes")
    with op.batch_alter_table("card_payments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_card_payments_card_id"))

    op.drop_table("card_payments")
    # ### end Alembic commands ###
