"""recurring charges

Revision ID: e9025e0b6791
Revises: 96d2eb7209c7
Create Date: 2026-09-30 16:59:37.579819
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "e9025e0b6791"
down_revision: str | None = "96d2eb7209c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recurring_charges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("subscription", "service", name="recurringkind", native_enum=False, length=15),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("amount_is_estimate", sa.Boolean(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column(
            "frequency",
            sa.Enum("monthly", "yearly", name="frequency", native_enum=False, length=15),
            nullable=False,
        ),
        sa.Column("day_of_month", sa.Integer(), nullable=False),
        sa.Column("month_of_year", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("next_run", sa.Date(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            "frequency != 'yearly' OR month_of_year BETWEEN 1 AND 12",
            name=op.f("ck_recurring_charges_yearly_has_month"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_recurring_charges_amount_positive")),
        sa.CheckConstraint(
            "day_of_month BETWEEN 1 AND 31", name=op.f("ck_recurring_charges_day_range")
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
            name=op.f("fk_recurring_charges_card_id_cards"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_recurring_charges_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recurring_charges")),
    )
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.add_column(sa.Column("recurring_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_expenses_recurring_id"), ["recurring_id"], unique=False
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_expenses_recurring_id"), ["recurring_id", "date"]
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_expenses_recurring_id_recurring_charges"),
            "recurring_charges",
            ["recurring_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_expenses_recurring_id_recurring_charges"), type_="foreignkey"
        )
        batch_op.drop_constraint(batch_op.f("uq_expenses_recurring_id"), type_="unique")
        batch_op.drop_index(batch_op.f("ix_expenses_recurring_id"))
        batch_op.drop_column("recurring_id")

    op.drop_table("recurring_charges")
    # ### end Alembic commands ###
